kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq-operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:default:rabbitmq-operator
roleRef:
  kind: ClusterRole
  name: rabbitmq-operator
  apiGroup: rbac.authorization.k8s.io
