apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.rabbitmq.improvado.io
spec:
  group: rabbitmq.improvado.io
  names:
    kind: Rabbitmq
    listKind: RabbitmqList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
