---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-operator
  template:
    metadata:
      labels:
        app: rabbitmq-operator
    spec:
      serviceAccountName: rabbitmq-operator
      containers:
        - name: rabbitmq-operator
          image: 716309063777.dkr.ecr.us-east-1.amazonaws.com/rabbitmq-operator:debug
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rabbitmq-operator"
            - name: WATCH_NAMESPACE
              value: "rabbit-operator-debug"

# create service for deployment

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-operator
spec:
  selector:
    app: rabbitmq-operator
  ports:
  - port: 80
